language: java
jdk:
  - oraclejdk8
script: 
  - ant build
  - mvn test jacoco:report
before install:
  - apt-get install commons-cli-java
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - mvn coveralls:report